### ISSUE TITLE
文档字符错误

### ISSUE THREAD

**Issue by ktKongTong** [developers-youcong/yc-framework#15]
Gitte->Gitee
![image](https://user-images.githubusercontent.com/44502608/162670158-ea2ab4d9-6722-4abf-a496-500e86d8679f.png)

**Comment by developers-youcong** [comment]
![image](https://user-images.githubusercontent.com/45055576/162895511-f6cb68d4-b904-47d0-9c8a-265210ef92a4.png)

**Comment by developers-youcong** [comment]
多谢指出
